apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-infra
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secrets-manager
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets", "events"]
  verbs:  ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sa-infra-secrets
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secrets-manager
subjects:
- kind: ServiceAccount
  name: sa-infra
  namespace: infra
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sealed-secrets-manager
rules:
- apiGroups: ["bitnami.com"]
  resources: ["sealedsecrets", "sealedsecrets/status"]
  verbs:  ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sa-infra-sealed-secrets
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sealed-secrets-manager
subjects:
- kind: ServiceAccount
  name: sa-infra
  namespace: infra
