apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-infra
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secrets-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs:  ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-infra-secrets
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secrets-reader
subjects:
- kind: ServiceAccount
  name: sa-infra
  namespace: infra
